### ISSUE TITLE
Reconfigure status checks

### ISSUE THREAD

**Issue by rudolf-adamkovic** [enfluid/hotline#21]
We need to reconfigure BuddyBuild "status check" on GitHub:

* Old:

    buddybuild: HotlineIO (iOS, HotlineIO - Debug)

* New:

    buddybuild: HotlineIO (iOS, HotlineIO)

**Comment by rudolf-adamkovic** [comment]
Also, please check for duplicate web hooks. There should be just one.

Something is not configured properly here.

**Comment by enfluid** [comment]
Done!

**Comment by rudolf-adamkovic** [comment]
Hm, GitHub still shows 2 pending checks:

<img width="782" alt="screen shot 2017-03-16 at 15 28 13" src="https://cloud.githubusercontent.com/assets/1158274/24001082/6df73f7e-0a5d-11e7-99da-2a27df16c504.png">

**Comment by rudolf-adamkovic** [comment]
Will open a new PR soon. Let's see.

**Comment by enfluid** [comment]
There's only one webhook, and definitely the debug one is unchecked, on both branches.  I just re-checked.

**Comment by rudolf-adamkovic** [comment]
Thanks for verifying. Maybe the non-required one will linger around for some time. Everything is 100% usable though. Closing for now.
